### PR TITLE
Lab 1

### PR DESCRIPTION
**Pull request by kurt3903**
Not sure if these files are readable?
@lucis-fluxum

### CODE REVIEW

**Comment by 0xSiO** [comment]
@kurt3903 Yep, no problem, I'll review tomorrow morning. My lab is ready too, take a look when you get the chance.

**Comment by 0xSiO** [comment]
Part 1:
- Write a bit about `erfc` and how it helps us calculate the integral
- Tell the reader what exactly you are integrating
- Write about what `norminv` does to give you a sigma value
- Might be better to overlay your PDF and histogram in different colors to show the similarity. Use the 'Normalization' option in the `histogram` function to scale it correctly

Part 2:
- Write about what the lognormal distribution actually is. Where does it come from?
- _... 100,000 data points with an approximately normal distribution ..._ 
Nope, this time they're lognormally distributed.
- _... all we have to do is integrate the probability distribution function from 2.0 to infinity. This is equivalent to reading the value of the cumulative distribution function at the value x = 2.0._ 
These statements are not equivalent. The CDF at 2 is equal to the integral from -Inf to 2, not 2 to Inf.
- _A measurement of the background at this threshold would be 2.77 standard deviations away from the mean of the distribution._
2.77 std deviations away from the mean of _which_ distribution?
- Love the plots for the lognormal and log of the lognormal distribution side by side at the end, good way to visualize it and prove your point

**Non-continuous distributions**
Part 1:
- _... we sum the probabilities corresponding to 15 events or more. This is equivalent to getting the value of the Poisson cumulative distribution function at x=15_
Same issue as my comment about the CDF above
- _... choosing an arbitrary value of sigma will likely yield zero probability ..._
But a value of sigma _is_ a probability. It would be more accurate to say you _cannot_ choose an arbitrary value for sigma because only the discrete values are defined for this distribution. Or maybe change the wording here entirely, I don't think we choose values for sigma anyway.
- _By increasing λ, the data becomes more linear, as the distribution becomes approximately Gaussian at large values of λ_
Maybe plot a histogram of the Poisson for a very large lambda and a Gaussian to show the approximation, kind of like when you took the log of the lognormal distribution and plotted them side by side

**Comment by kurt3903** [comment]
> Part 1:
> 
> * Write a bit about `erfc` and how it helps us calculate the integral
> * Tell the reader what exactly you are integrating
> * Write about what `norminv` does to give you a sigma value
> * Might be better to overlay your PDF and histogram in different colors to show the similarity. Use the 'Normalization' option in the `histogram` function to scale it correctly
> 
> Part 2:
> 
> * Write about what the lognormal distribution actually is. Where does it come from?
> * _... 100,000 data points with an approximately normal distribution ..._
>   Nope, this time they're lognormally distributed.
> * _... all we have to do is integrate the probability distribution function from 2.0 to infinity. This is equivalent to reading the value of the cumulative distribution function at the value x = 2.0._
>   These statements are not equivalent. The CDF at 2 is equal to the integral from -Inf to 2, not 2 to Inf.
> * _A measurement of the background at this threshold would be 2.77 standard deviations away from the mean of the distribution._
>   2.77 std deviations away from the mean of _which_ distribution?
> * Love the plots for the lognormal and log of the lognormal distribution side by side at the end, good way to visualize it and prove your point
> 
> **Non-continuous distributions**
> Part 1:
> 
> * _... we sum the probabilities corresponding to 15 events or more. This is equivalent to getting the value of the Poisson cumulative distribution function at x=15_
>   Same issue as my comment about the CDF above
> * _... choosing an arbitrary value of sigma will likely yield zero probability ..._
>   But a value of sigma _is_ a probability. It would be more accurate to say you _cannot_ choose an arbitrary value for sigma because only the discrete values are defined for this distribution. Or maybe change the wording here entirely, I don't think we choose values for sigma anyway.
> * _By increasing λ, the data becomes more linear, as the distribution becomes approximately Gaussian at large values of λ_
>   Maybe plot a histogram of the Poisson for a very large lambda and a Gaussian to show the approximation, kind of like when you took the log of the lognormal distribution and plotted them side by side

Thank you for the feedback! I am working on making comments for your lab report now, I have been at work all day.

**Comment by sfzhu** [comment]
erfc gives the area of right tail, that's the probability greater than a certain value.

**Pull request merged**
